import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {step,G} from './physics.mjs?v=2';
const $=id=>document.getElementById(id), AU=10, EARTH=332946;
const renderer=new T.WebGLRenderer({canvas:$('universe'),antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;
const scene=new T.Scene();scene.background=new T.Color('#050a12');
const camera=new T.PerspectiveCamera(45,innerWidth/innerHeight,.01,5000);camera.position.set(32,45,84);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=1;controls.maxDistance=900;controls.target.set(0,0,0);
scene.add(new T.HemisphereLight(0xb8d7ff,0x10151f,.52));
const sunlight=new T.PointLight(0xfff4df,55,0,1);scene.add(sunlight);
const geometry=new T.SphereGeometry(1,64,40);
const textureLoader=new T.TextureLoader();const earthTexture=textureLoader.load('./assets/earth.jpg');earthTexture.colorSpace=T.SRGBColorSpace;
let bodies=[],selected=null,following=false,playing=true,years=0,id=0;const effects=[];
const random=(seed)=>{let s=seed;return()=>((s=s*16807%2147483647)-1)/2147483646};
function surface(type,seed){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=random(seed+191);x.fillStyle=type==='gas'?'#c4b297':'#8b8c86';x.fillRect(0,0,512,256);for(let i=0;i<1800;i++){if(type==='gas'){const y=r()*256;x.fillStyle=`rgba(${r()>.5?'93,74,59':'236,216,181'},${r()*.22})`;x.fillRect(0,y,512,r()*5+1)}else{x.fillStyle=`rgba(${r()>.5?'35,30,26':'235,227,209'},${r()*.2})`;x.beginPath();x.arc(r()*512,r()*256,r()*4+.5,0,7);x.fill()}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
function halo(color){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,64);g.addColorStop(0,'#ffffff');g.addColorStop(.13,color);g.addColorStop(.3,color+'44');g.addColorStop(1,color+'00');x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c)}
const glowMap=halo('#ffd5a0');
const starGeo=new T.BufferGeometry(),positions=[],colors=[];const rng=random(333);for(let i=0;i<6500;i++){const angle=rng()*Math.PI*2;const z=i<4200?(rng()+rng()+rng()-1.5)*.28:rng()*2-1;const rr=Math.sqrt(Math.max(0,1-z*z)),dist=650+rng()*600;positions.push(Math.cos(angle)*rr*dist,z*dist,Math.sin(angle)*rr*dist);const c=new T.Color(rng()<.2?'#ffe1b6':'#bbd8ff');c.multiplyScalar(.25+rng()*.75);colors.push(c.r,c.g,c.b)}starGeo.setAttribute('position',new T.Float32BufferAttribute(positions,3));starGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));scene.add(new T.Points(starGeo,new T.PointsMaterial({size:1.1,vertexColors:true,transparent:true,opacity:.85,sizeAttenuation:true})));
const selectionRing=new T.Mesh(new T.RingGeometry(1.15,1.17,96),new T.MeshBasicMaterial({color:0xa7e6df,side:T.DoubleSide,transparent:true,opacity:.65}));scene.add(selectionRing);
function create(spec){const b={id:++id,name:'World '+id,type:'rock',mass:1/EARTH,radius:.45,color:'#adbac2',p:[0,0,0],v:[0,0,0],tilt:23,atmo:.08,atmoColor:'#76bfff',magnetic:1,gravity:1,water:20,ice:8,ocean:'#174a8b',land:'#617c4a',impacts:0,temp:280,trail:[],...spec};
 const map=b.name==='Earth'?earthTexture:surface(b.type,b.id);b.material=new T.MeshStandardMaterial({map:b.type==='star'||b.type==='blackhole'?null:map,color:b.name==='Earth'?'#ffffff':b.color,roughness:.86,metalness:0});
 if(b.type==='star'){b.material.emissive=new T.Color(b.color);b.material.emissiveIntensity=2.5}if(b.type==='blackhole'){b.material.color.set('#000000');b.material.roughness=1}
 b.mesh=new T.Mesh(geometry,b.material);b.mesh.userData.body=b;scene.add(b.mesh);
 b.atmosphere=new T.Mesh(geometry,new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,uniforms:{tint:{value:new T.Color(0x76bfff)},strength:{value:b.atmo}},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.); n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 tint; uniform float strength; varying vec3 n;varying vec3 v;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(v))),3.);gl_FragColor=vec4(tint,rim*strength);}' }));scene.add(b.atmosphere);
 b.axis=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0,-1.6,0),new T.Vector3(0,1.6,0)]),new T.LineBasicMaterial({color:0x9fdacf,transparent:true,opacity:.5}));b.mesh.add(b.axis);b.field=new T.Group();for(let q=0;q<3;q++){const loop=new T.Mesh(new T.TorusGeometry(1.25+q*.22,.008,8,72),new T.MeshBasicMaterial({color:0x69d8ff,transparent:true,opacity:.16-q*.03,blending:T.AdditiveBlending,depthWrite:false}));loop.rotation.set(Math.PI/2,q*.42,q*.63);b.field.add(loop)}scene.add(b.field);
 if(b.type==='star'){b.glow=new T.Sprite(new T.SpriteMaterial({map:glowMap,color:b.color,blending:T.AdditiveBlending,transparent:true,depthWrite:false}));scene.add(b.glow)}
 if(b.ring||b.type==='blackhole'){const ringGeo=new T.RingGeometry(b.type==='blackhole'?1.5:1.35,2.3,128,4);b.ringMesh=new T.Mesh(ringGeo,new T.MeshBasicMaterial({color:b.type==='blackhole'?0xffb76b:0xbaad92,side:T.DoubleSide,transparent:true,opacity:.58}));b.ringMesh.rotation.x=Math.PI/2.3;scene.add(b.ringMesh)}
 b.line=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:b.type==='star'?0xffd486:b.color,transparent:true,opacity:.82,blending:T.AdditiveBlending,depthWrite:false}));scene.add(b.line);bodies.push(b);return b;
}
function refreshSurface(b){if(b.type==='star'||b.type==='blackhole'||b.type==='gas')return;const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=random(b.id*991+37);x.fillStyle=b.water>0?b.ocean:b.color;x.fillRect(0,0,512,256);const landShare=1-b.water/100;x.fillStyle=b.land;for(let i=0;i<120*landShare;i++){const px=r()*512,py=25+r()*206,w=8+r()*38,h=4+r()*18;x.beginPath();x.ellipse(px,py,w,h,r()*3,0,7);x.fill()}if(b.ice>0){x.fillStyle='#eaf7ff';const h=Math.max(2,b.ice*.55);x.fillRect(0,0,512,h);x.fillRect(0,256-h,512,h)}const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;if(b.material.map!==earthTexture)b.material.map?.dispose();b.material.map=map;b.material.color.set('#ffffff');b.material.needsUpdate=true}
function setRings(b,on=!b.ring){b.ring=on;if(b.ringMesh){scene.remove(b.ringMesh);b.ringMesh.geometry.dispose();b.ringMesh.material.dispose();delete b.ringMesh}if(on||b.type==='blackhole'){const ringGeo=new T.RingGeometry(b.type==='blackhole'?1.5:1.35,2.3,128,4);b.ringMesh=new T.Mesh(ringGeo,new T.MeshBasicMaterial({color:b.type==='blackhole'?0xffb76b:0xc7b997,side:T.DoubleSide,transparent:true,opacity:.72,blending:T.AdditiveBlending,depthWrite:false}));b.ringMesh.rotation.x=Math.PI/2.3;scene.add(b.ringMesh)}}
function destroy(b){for(const key of ['mesh','atmosphere','glow','ringMesh','line','field'])if(b[key])scene.remove(b[key]);b.material.map!==earthTexture&&b.material.map?.dispose();b.material.dispose();b.atmosphere.material.dispose();b.line.geometry.dispose();b.line.material.dispose();b.glow?.material.dispose();b.ringMesh?.geometry.dispose();b.ringMesh?.material.dispose();b.field?.children.forEach(x=>{x.geometry.dispose();x.material.dispose()});b.axis.geometry.dispose();b.axis.material.dispose();bodies=bodies.filter(x=>x!==b)}
function choose(b){selected=b;following=false;if(!b){$('inspector').hidden=true;return}$('inspector').hidden=false;$('title').textContent=b.name;$('kind').textContent={star:'Stellar body',rock:'Terrestrial world',gas:'Gas giant',moon:'Natural satellite',blackhole:'Compact object'}[b.type];$('name').value=b.name;$('mass').value=(b.mass*EARTH).toPrecision(5);$('color').value=b.color;$('radius').value=b.radius;$('tilt').value=b.tilt;$('gravity').value=b.gravity;$('vx').value=b.v[0].toFixed(3);$('vy').value=b.v[1].toFixed(3);$('vz').value=b.v[2].toFixed(3);$('water').value=b.water;$('ice').value=b.ice;$('ocean').value=b.ocean;$('land').value=b.land;$('atmo').value=b.atmo;$('atmoColor').value=b.atmoColor;$('magnetic').value=b.magnetic;$('impacts').textContent=b.impacts;syncOutputs(b);notice(b.name+' selected · double-click to follow')}
function syncOutputs(b){$('tiltValue').textContent=b.tilt+'°';$('gravityValue').textContent=b.gravity.toFixed(2)+'×';$('waterValue').textContent=Math.round(b.water)+'%';$('iceValue').textContent=Math.round(b.ice)+'%';$('atmoValue').textContent=b.atmo.toFixed(2)+' atm';$('magneticValue').textContent=b.magnetic.toFixed(1)+'×'}
function notice(s){$('message').textContent=s}
function orbit(parent,spec,distance,angle=Math.random()*Math.PI*2,inclination=.03){const speed=Math.sqrt(G*(parent.mass+(spec.mass||1/EARTH))/distance);return create({...spec,p:[parent.p[0]+Math.cos(angle)*distance,parent.p[1]+Math.sin(angle)*distance*Math.sin(inclination),parent.p[2]+Math.sin(angle)*distance*Math.cos(inclination)],v:[parent.v[0]-Math.sin(angle)*speed,parent.v[1]+Math.cos(angle)*speed*Math.sin(inclination),parent.v[2]+Math.cos(angle)*speed*Math.cos(inclination)]})}
function solar(){for(const b of [...bodies])destroy(b);years=0;const sun=create({name:'Sun',type:'star',mass:1,radius:1.6,color:'#fff0cb',temp:5778,atmo:0,water:0,ice:0,magnetic:.02});const data=[['Mercury',.39,.055,.19,'#9e9389'],['Venus',.72,.815,.33,'#d7c6a5'],['Earth',1,1,.36,'#79b6ff'],['Mars',1.52,.107,.27,'#b87453'],['Jupiter',5.2,317.8,.94,'#c8b399'],['Saturn',9.58,95.2,.80,'#d3c39b'],['Uranus',19.2,14.5,.61,'#98cbd0'],['Neptune',30.05,17.1,.59,'#739cc4']];const planets={};data.forEach((d,i)=>{const b=orbit(sun,{name:d[0],mass:d[2]/EARTH,radius:d[3],color:d[4],type:i>3?'gas':'rock',ring:i===5,atmo:i===0?0:(i===2?1:.3),tilt:i===6?98:23,temp:i===2?288:120,water:i===2?71:(i===3?2:0),ice:i===2?18:(i===3?12:0),magnetic:i===2?1:(i===4?4.3:.25)},d[1],i*.79+.4,i===0?.12:.025);planets[d[0]]=b});const moon=(parent,name,mass,radius,distance,angle)=>orbit(parent,{name,type:'moon',mass:mass/EARTH,radius,color:'#aaa89f',atmo:0,water:2,ice:18,magnetic:.05},distance,angle,.15);moon(planets.Earth,'Moon',.0123,.10,.10,0);moon(planets.Jupiter,'Io',.015,.07,.14,.3);moon(planets.Jupiter,'Europa',.008,.065,.19,1.4);moon(planets.Jupiter,'Ganymede',.025,.085,.25,2.5);moon(planets.Jupiter,'Callisto',.018,.08,.32,3.7);moon(planets.Saturn,'Titan',.0225,.085,.20,.8);moon(planets.Uranus,'Titania',.00059,.055,.16,2.2);moon(planets.Neptune,'Triton',.0036,.065,.16,4.1);choose(planets.Earth);camera.position.set(24,30,57);controls.target.set(0,0,0);notice('Solar system ready · 8 planets and 8 major moons');}
function spawn(type){if(bodies.length>=60){notice('60-body limit reached');return}const parent=selected||bodies.find(b=>b.type==='star');if(!parent){choose(create({type}));return}const specs={rock:{name:'New rocky world',type:'rock',radius:.4,color:'#b29c85'},gas:{name:'New gas giant',type:'gas',mass:80/EARTH,radius:.85,color:'#bca78d',ring:true},moon:{name:'New moon',type:'moon',mass:.012/EARTH,radius:.12,color:'#aaa9a0',atmo:0},star:{name:'Companion star',type:'star',mass:.3,radius:1.2,color:'#ffd2a5',atmo:0,temp:3800},blackhole:{name:'Black hole',type:'blackhole',mass:3,radius:.6,color:'#000000',atmo:0}};const s=specs[type];const d=Math.max((parent.radius+s.radius)*.3,parent.type==='star'?3:.35);choose(orbit(parent,s,d));notice('Created '+selected.name+' in a 3D orbit')}
function impact(){if(!selected)return;const target=selected,boost=Number($('impactSpeed').value);const offset=(target.radius+.15)/AU*1.1;create({name:'Impactor',type:'moon',mass:.08/EARTH,radius:.1,color:'#665c53',atmo:.02,water:8,ice:12,p:[target.p[0]+offset,target.p[1]+offset*.3,target.p[2]],v:[target.v[0]-15*boost,target.v[1]-4.5*boost,target.v[2]]});notice(['Slow','Fast','Hypervelocity'][boost<.8?0:boost<1.3?1:2]+' impactor launched toward '+target.name)}
function collide(){for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){let a=bodies[i],b=bodies[j];if(Math.hypot(...a.p.map((v,k)=>v-b.p[k]))>(a.radius+b.radius)/AU*.65)continue;if(b.mass>a.mass)[a,b]=[b,a];const am=a.mass,bm=b.mass,m=am+bm,dv=Math.hypot(...a.v.map((v,k)=>v-b.v[k])),strip=Math.max(.03,1-dv*.035);a.v=a.v.map((v,k)=>(v*am+b.v[k]*bm)/m);a.p=a.p.map((v,k)=>(v*am+b.p[k]*bm)/m);a.atmo=((a.atmo*am+b.atmo*bm)/m)*strip;a.water=(a.water*am+b.water*bm)/m;a.ice=Math.max(0,(a.ice*am+b.ice*bm)/m-dv*.4);a.magnetic=(a.magnetic*am+b.magnetic*bm)/m;a.mass=m;a.radius=Math.cbrt(a.radius**3+b.radius**3);a.temp=Math.min(15000,a.temp+dv*300);a.impacts=(a.impacts||0)+(b.impacts||0)+1;a.heat=1;refreshSurface(a);const wave=new T.Mesh(new T.SphereGeometry(1,24,16),new T.MeshBasicMaterial({color:dv>12?0xfff0c2:0xffa45d,wireframe:true,transparent:true,opacity:.8,blending:T.AdditiveBlending,depthWrite:false}));wave.position.set(...a.p.map(v=>v*AU));scene.add(wave);effects.push({mesh:wave,age:0,r:a.radius});const wasSelected=selected===b||selected===a,hitName=b.name;destroy(b);if(wasSelected)choose(a);notice(a.name+' absorbed '+hitName+' · '+Math.round((1-strip)*100)+'% atmosphere stripped · surface reheated');return}}
function stellarBurst(kind){if(!selected||selected.type!=='star'){notice('Select a star to trigger this event');return}const star=selected,verts=[],r=random(Date.now()%99991);for(let i=0;i<180;i++){const v=new T.Vector3(r()*2-1,r()*2-1,r()*2-1).normalize().multiplyScalar(.7+r()*.7);verts.push(v.x,v.y,v.z)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));const cloud=new T.Points(geo,new T.PointsMaterial({color:kind==='flare'?0xffc36b:0xeaf6ff,size:.07,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false}));cloud.position.copy(star.mesh.position);scene.add(cloud);effects.push({mesh:cloud,age:0,r:star.radius});for(const b of bodies){if(b===star)continue;const d=Math.max(.1,Math.hypot(...b.p.map((v,i)=>v-star.p[i])));b.temp+=kind==='flare'?Math.min(700,80/d):Math.min(6000,1200/d);if(kind==='supernova')b.v=b.v.map((v,i)=>v+(b.p[i]-star.p[i])/d*.18/d)}if(kind==='supernova'){star.type='blackhole';star.color='#000000';star.mass=Math.max(3,star.mass*.25);star.radius=.7;star.atmo=0;star.material.map=null;star.material.color.set('#000000');star.material.emissive.set('#000000');setRings(star,true);choose(star);notice('Supernova erupted · remnant collapsed into a black hole')}else notice('Coronal mass ejection released · nearby worlds heated')}
const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(bodies.map(b=>b.mesh),false)[0];if(hit)choose(hit.object.userData.body)});renderer.domElement.addEventListener('dblclick',()=>follow());controls.addEventListener('start',()=>following=false);
function follow(){if(!selected)return;following=true;const pos=selected.mesh.position;controls.target.copy(pos);camera.position.copy(pos).add(new T.Vector3(selected.radius*5,selected.radius*3,selected.radius*8));notice('Following '+selected.name)}
$('focus').onclick=follow;$('impact').onclick=impact;$('reset').onclick=solar;$('clear').onclick=()=>{for(const b of [...bodies])destroy(b);choose(null);years=0;notice('Universe cleared · add a body to begin')};$('fit').onclick=()=>{following=false;controls.target.set(0,0,0);const extent=Math.max(10,...bodies.map(b=>Math.hypot(...b.p)*AU));camera.position.set(extent*.5,extent*.9,extent*1.6)};$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'Ⅱ':'▶';$('pause').setAttribute('aria-label',playing?'Pause':'Play')};$('rings').onclick=()=>{if(selected){setRings(selected);notice((selected.ring?'Rings generated around ':'Rings removed from ')+selected.name)}};$('blackhole').onclick=()=>{if(!selected)return;selected.type='blackhole';selected.mass=Math.max(selected.mass,3);selected.atmo=0;selected.color='#000000';selected.material.map=null;selected.material.color.set('#000000');selected.material.emissive.set('#000000');setRings(selected,true);choose(selected);notice(selected.name+' collapsed into a black hole')};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>spawn(b.dataset.type));
$('name').oninput=e=>{if(selected){selected.name=e.target.value;$('title').textContent=selected.name}};$('mass').onchange=e=>{const n=Number(e.target.value);if(selected&&Number.isFinite(n)&&n>0&&n<1e9)selected.mass=n/EARTH};$('color').oninput=e=>{if(selected){selected.color=e.target.value;selected.material.color.set(e.target.value);if(selected.type==='star')selected.material.emissive.set(e.target.value)}};for(const [field,key]of [['radius','radius'],['tilt','tilt'],['atmo','atmo'],['gravity','gravity'],['water','water'],['ice','ice'],['magnetic','magnetic']])$(field).oninput=e=>{if(selected){selected[key]=Number(e.target.value);syncOutputs(selected);if(key==='water'||key==='ice')refreshSurface(selected)}};for(const [field,key]of [['ocean','ocean'],['land','land'],['atmoColor','atmoColor']])$(field).oninput=e=>{if(selected){selected[key]=e.target.value;if(key!=='atmoColor')refreshSurface(selected)}};for(const [field,i]of [['vx',0],['vy',1],['vz',2]])$(field).onchange=e=>{const n=Number(e.target.value);if(selected&&Number.isFinite(n))selected.v[i]=n};$('remove').onclick=()=>{if(selected){destroy(selected);choose(bodies[0]||null)}};window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.code==='Space'){e.preventDefault();$('pause').click()}if(e.key.toLowerCase()==='f')follow();if((e.key==='Delete'||e.key==='Backspace')&&selected)$('remove').click()});
const serial=b=>Object.fromEntries(['name','type','mass','radius','color','p','v','tilt','atmo','atmoColor','magnetic','gravity','water','ice','ocean','land','impacts','temp','ring'].map(k=>[k,b[k]]));$('save').onclick=()=>{try{localStorage.setItem('orbital3d',JSON.stringify({years,bodies:bodies.map(serial)}));notice('Universe saved on this device')}catch{notice('Could not save: browser storage unavailable')}};$('load').onclick=()=>{try{const data=JSON.parse(localStorage.getItem('orbital3d'));if(!data?.bodies?.length||data.bodies.length>60)throw Error();for(const b of data.bodies){if(!b.p?.every(Number.isFinite)||!b.v?.every(Number.isFinite)||!Number.isFinite(b.mass)||b.mass<=0)throw Error()}for(const b of [...bodies])destroy(b);data.bodies.forEach(create);years=data.years||0;choose(bodies[0]);notice('Saved universe restored')}catch{notice('No valid saved universe on this device')}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});let last=performance.now(),frame=0;
function animate(now){requestAnimationFrame(animate);const real=Math.max(0,Math.min((now-last)/1000,.05));last=now;if(playing){const requested=real*Number($('speed').value);let safe=.001;for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],d=Math.hypot(...a.p.map((v,k)=>v-b.p[k]));safe=Math.min(safe,Math.sqrt(Math.max(d,1e-5)**3/(G*(a.mass+b.mass)))/30)}const n=Math.min(50,Math.max(1,Math.ceil(requested/safe))),dt=Math.min(safe,requested/n);for(let k=0;k<n;k++){step(bodies,dt);collide()}years+=dt*n}
 for(const b of bodies){const shown=b.type!=='moon'||$('moons').checked;b.mesh.position.set(...b.p.map(v=>v*AU));b.mesh.scale.setScalar(b.radius);b.mesh.rotation.z=T.MathUtils.degToRad(b.tilt);b.mesh.visible=shown;if(playing)b.mesh.rotation.y+=real*.08;b.atmosphere.position.copy(b.mesh.position);b.atmosphere.scale.setScalar(b.radius*1.045);b.atmosphere.material.uniforms.strength.value=Math.min(1.2,b.atmo*.32);b.atmosphere.material.uniforms.tint.value.set(b.atmoColor);b.atmosphere.visible=shown&&b.atmo>0&&b.type!=='star';b.axis.visible=shown&&$('axes').checked;if(b.glow){b.glow.position.copy(b.mesh.position);b.glow.scale.setScalar(b.radius*9)}if(b.ringMesh){b.ringMesh.position.copy(b.mesh.position);b.ringMesh.scale.setScalar(b.radius);b.ringMesh.visible=shown}if(b.type!=='blackhole'){if(b.heat){b.heat=Math.max(0,b.heat-real*.09);b.material.emissive.set('#ff450b');b.material.emissiveIntensity=.06+b.heat*1.3}else{b.material.emissive.set(b.type==='star'?b.color:b.color);b.material.emissiveIntensity=b.type==='star'?2.5:.06}}b.line.visible=shown&&$('trails').checked;if(playing&&frame%4===0){b.trail.push(b.mesh.position.clone());const max=Number($('trailLength').value);if(b.trail.length>max)b.trail.splice(0,b.trail.length-max);b.line.geometry.dispose();b.line.geometry=new T.BufferGeometry().setFromPoints(b.trail)}}
const sun=bodies.find(b=>b.type==='star');sunlight.visible=!!sun;if(sun)sunlight.position.copy(sun.mesh.position);if(selected){selectionRing.visible=selected.mesh.visible;selectionRing.position.copy(selected.mesh.position);selectionRing.scale.setScalar(selected.radius);selectionRing.quaternion.copy(camera.quaternion);$('temp').textContent=Math.round(selected.temp)+' K';$('velocity').textContent=(Math.hypot(...selected.v)*4.74).toFixed(1)+' km/s';$('impacts').textContent=selected.impacts||0;if(following){const d=selected.mesh.position.clone().sub(controls.target);camera.position.add(d);controls.target.copy(selected.mesh.position)}}else selectionRing.visible=false;
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=real;e.mesh.scale.setScalar(e.r*(1+e.age*4));e.mesh.material.opacity=Math.max(0,.6-e.age*.25);if(e.age>2.4){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}
 $('clock').textContent=(years*365.25).toFixed(1)+' days';$('count').textContent=bodies.length+' bodies · '+(playing?'simulation running':'paused');controls.update();renderer.render(scene,camera);frame++}
solar();requestAnimationFrame(animate);
