import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {step,G} from './physics.mjs?v=2';
const $=id=>document.getElementById(id), AU=10, EARTH=332946;
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const renderer=new T.WebGLRenderer({canvas:$('universe'),antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;
const scene=new T.Scene();scene.background=new T.Color('#050a12');
const camera=new T.PerspectiveCamera(45,innerWidth/innerHeight,.01,5000);camera.position.set(32,45,84);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=1;controls.maxDistance=900;controls.target.set(0,0,0);
scene.add(new T.HemisphereLight(0xb8d7ff,0x10151f,.52));
const sunlight=new T.PointLight(0xfff4df,55,0,1);scene.add(sunlight);const asteroidBelt=new T.Group();asteroidBelt.name='Asteroid Belt';scene.add(asteroidBelt);const orbitGuides=new T.Group();orbitGuides.name='Orbit guides';scene.add(orbitGuides);
function buildAsteroidBelt(){asteroidBelt.clear();const positions=[],r=random(8731);for(let i=0;i<520;i++){const angle=r()*Math.PI*2;const distance=20.5+r()*11.5;const y=(r()-.5)*(0.4+r()*1.1);positions.push(Math.cos(angle)*distance,y,Math.sin(angle)*distance)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));asteroidBelt.add(new T.Points(geo,new T.PointsMaterial({color:0xbda78e,size:.09,transparent:true,opacity:.82,sizeAttenuation:true,depthWrite:false})))}
const geometry=new T.SphereGeometry(1,64,40);
const textureLoader=new T.TextureLoader();const earthTexture=textureLoader.load('./assets/earth.jpg');earthTexture.colorSpace=T.SRGBColorSpace;
let bodies=[],selected=null,following=false,playing=true,years=0,id=0,placeSpec=null,moveMode=false,moving=null,launchTargetId=null;const followOffset=new T.Vector3();const effects=[];
const random=(seed)=>{let s=seed;return()=>((s=s*16807%2147483647)-1)/2147483646};
function surface(type,seed){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=random(seed+191);x.fillStyle=type==='gas'?'#c4b297':'#8b8c86';x.fillRect(0,0,512,256);for(let i=0;i<1800;i++){if(type==='gas'){const y=r()*256;x.fillStyle=`rgba(${r()>.5?'93,74,59':'236,216,181'},${r()*.22})`;x.fillRect(0,y,512,r()*5+1)}else{x.fillStyle=`rgba(${r()>.5?'35,30,26':'235,227,209'},${r()*.2})`;x.beginPath();x.arc(r()*512,r()*256,r()*4+.5,0,7);x.fill()}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
function halo(color){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,64);g.addColorStop(0,'#ffffff');g.addColorStop(.13,color);g.addColorStop(.3,color+'44');g.addColorStop(1,color+'00');x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c)}
const glowMap=halo('#ffd5a0');
const starGeo=new T.BufferGeometry(),positions=[],colors=[];const rng=random(333);for(let i=0;i<6500;i++){const angle=rng()*Math.PI*2;const z=i<4200?(rng()+rng()+rng()-1.5)*.28:rng()*2-1;const rr=Math.sqrt(Math.max(0,1-z*z)),dist=650+rng()*600;positions.push(Math.cos(angle)*rr*dist,z*dist,Math.sin(angle)*rr*dist);const c=new T.Color(rng()<.2?'#ffe1b6':'#bbd8ff');c.multiplyScalar(.25+rng()*.75);colors.push(c.r,c.g,c.b)}starGeo.setAttribute('position',new T.Float32BufferAttribute(positions,3));starGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));scene.add(new T.Points(starGeo,new T.PointsMaterial({size:1.1,vertexColors:true,transparent:true,opacity:.85,sizeAttenuation:true})));
const selectionRing=new T.Mesh(new T.RingGeometry(1.15,1.17,96),new T.MeshBasicMaterial({color:0xa7e6df,side:T.DoubleSide,transparent:true,opacity:.65}));scene.add(selectionRing);const placementRing=new T.Mesh(new T.RingGeometry(1.2,1.28,96),new T.MeshBasicMaterial({color:0xffe19d,side:T.DoubleSide,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false}));placementRing.rotation.x=-Math.PI/2;placementRing.visible=false;scene.add(placementRing);
function create(spec){const b={id:++id,name:'World '+id,type:'rock',mass:1/EARTH,radius:.45,color:'#adbac2',p:[0,0,0],v:[0,0,0],tilt:23,dayLength:24,atmo:.08,atmoColor:'#76bfff',magnetic:1,gravity:1,water:20,ice:8,ocean:'#174a8b',land:'#617c4a',impacts:0,temp:280,trail:[],parentId:null,...spec};
 const map=b.name==='Earth'?earthTexture:surface(b.type,b.id);b.material=new T.MeshStandardMaterial({map:b.type==='star'||b.type==='blackhole'?null:map,color:b.name==='Earth'?'#ffffff':b.color,roughness:.86,metalness:0});
 if(b.type==='star'){b.material.emissive=new T.Color(b.color);b.material.emissiveIntensity=2.5}if(b.type==='blackhole'){b.material.color.set('#000000');b.material.roughness=1}
 b.mesh=new T.Mesh(geometry,b.material);b.mesh.userData.body=b;scene.add(b.mesh);
 b.atmosphere=new T.Mesh(geometry,new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,uniforms:{tint:{value:new T.Color(0x76bfff)},strength:{value:b.atmo}},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.); n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 tint; uniform float strength; varying vec3 n;varying vec3 v;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(v))),3.);gl_FragColor=vec4(tint,rim*strength);}' }));scene.add(b.atmosphere);
 b.axis=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0,-1.6,0),new T.Vector3(0,1.6,0)]),new T.LineBasicMaterial({color:0x9fdacf,transparent:true,opacity:.5}));b.mesh.add(b.axis);b.field=new T.Group();for(let q=0;q<3;q++){const loop=new T.Mesh(new T.TorusGeometry(1.25+q*.22,.008,8,72),new T.MeshBasicMaterial({color:0x69d8ff,transparent:true,opacity:.16-q*.03,blending:T.AdditiveBlending,depthWrite:false}));loop.rotation.set(Math.PI/2,q*.42,q*.63);b.field.add(loop)}scene.add(b.field);
 if(b.type==='star'){b.glow=new T.Sprite(new T.SpriteMaterial({map:glowMap,color:b.color,blending:T.AdditiveBlending,transparent:true,depthWrite:false}));scene.add(b.glow)}
 if(b.ring||b.type==='blackhole'){const ringGeo=new T.RingGeometry(b.type==='blackhole'?1.5:1.35,2.3,128,4);b.ringMesh=new T.Mesh(ringGeo,new T.MeshBasicMaterial({color:b.type==='blackhole'?0xffb76b:0xbaad92,side:T.DoubleSide,transparent:true,opacity:.58}));b.ringMesh.rotation.x=Math.PI/2.3;scene.add(b.ringMesh)}
 b.line=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:b.type==='star'?0xffd486:b.color,transparent:true,opacity:.82,blending:T.AdditiveBlending,depthWrite:false}));scene.add(b.line);bodies.push(b);syncCreatorTargets();return b;
}
function refreshSurface(b){if(b.type==='star'||b.type==='blackhole'||b.type==='gas')return;const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=random(b.id*991+37);x.fillStyle=b.water>0?b.ocean:b.color;x.fillRect(0,0,512,256);const landShare=1-b.water/100;x.fillStyle=b.land;for(let i=0;i<120*landShare;i++){const px=r()*512,py=25+r()*206,w=8+r()*38,h=4+r()*18;x.beginPath();x.ellipse(px,py,w,h,r()*3,0,7);x.fill()}if(b.ice>0){x.fillStyle='#eaf7ff';const h=Math.max(2,b.ice*.55);x.fillRect(0,0,512,h);x.fillRect(0,256-h,512,h)}const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;if(b.material.map!==earthTexture)b.material.map?.dispose();b.material.map=map;b.material.color.set('#ffffff');b.material.needsUpdate=true}
function addImpactHotspot(target,source,intensity){if(!target||target.type==='blackhole')return;target.hotspots??=[];const dx=source.p[0]-target.p[0],dz=source.p[2]-target.p[2],length=Math.hypot(dx,dz)||1;const hotspot=new T.Mesh(new T.SphereGeometry(.22,24,16),new T.MeshBasicMaterial({color:0xff6b24,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false}));hotspot.position.set((dx/length)*.72,.12,(dz/length)*.72);target.mesh.add(hotspot);target.hotspots.push({mesh:hotspot,age:0,strength:clamp(intensity,.35,1.2)});if(target.hotspots.length>4){const old=target.hotspots.shift();target.mesh.remove(old.mesh);old.mesh.geometry.dispose();old.mesh.material.dispose()}}
function setRings(b,on=!b.ring){b.ring=on;if(b.ringMesh){scene.remove(b.ringMesh);b.ringMesh.geometry.dispose();b.ringMesh.material.dispose();delete b.ringMesh}if(on||b.type==='blackhole'){const ringGeo=new T.RingGeometry(b.type==='blackhole'?1.5:1.35,2.3,128,4);b.ringMesh=new T.Mesh(ringGeo,new T.MeshBasicMaterial({color:b.type==='blackhole'?0xffb76b:0xc7b997,side:T.DoubleSide,transparent:true,opacity:.72,blending:T.AdditiveBlending,depthWrite:false}));b.ringMesh.rotation.x=Math.PI/2.3;scene.add(b.ringMesh)}}
function destroy(b){for(const key of ['mesh','atmosphere','glow','ringMesh','line','field'])if(b[key])scene.remove(b[key]);b.hotspots?.forEach(h=>{b.mesh.remove(h.mesh);h.mesh.geometry.dispose();h.mesh.material.dispose()});b.material.map!==earthTexture&&b.material.map?.dispose();b.material.dispose();b.atmosphere.material.dispose();b.line.geometry.dispose();b.line.material.dispose();b.glow?.material.dispose();b.ringMesh?.geometry.dispose();b.ringMesh?.material.dispose();b.field?.children.forEach(x=>{x.geometry.dispose();x.material.dispose()});b.axis.geometry.dispose();b.axis.material.dispose();bodies=bodies.filter(x=>x!==b);if(launchTargetId===b.id)launchTargetId=null;bodies.forEach(x=>{if(x.parentId===b.id)x.parentId=null});syncCreatorTargets()}
function choose(b){selected=b;following=false;if(!b){$('inspector').hidden=true;return}$('inspector').hidden=false;$('title').textContent=b.name;$('kind').textContent={star:'Stellar body',rock:'Terrestrial world',gas:'Gas giant',moon:'Natural satellite',blackhole:'Compact object'}[b.type];$('name').value=b.name;$('mass').value=(b.mass*EARTH).toPrecision(5);$('color').value=b.color;$('radius').value=b.radius;$('tilt').value=b.tilt;$('dayLength').value=b.dayLength;$('gravity').value=b.gravity;$('vx').value=b.v[0].toFixed(3);$('vy').value=b.v[1].toFixed(3);$('vz').value=b.v[2].toFixed(3);$('water').value=b.water;$('ice').value=b.ice;$('ocean').value=b.ocean;$('land').value=b.land;$('atmo').value=b.atmo;$('atmoColor').value=b.atmoColor;$('magnetic').value=b.magnetic;$('impacts').textContent=b.impacts;syncOutputs(b);syncBodyCard(b);notice(b.name+' selected · double-click to follow')}
function syncOutputs(b){$('tiltValue').textContent=b.tilt+'°';$('dayValue').textContent=Math.round(b.dayLength)+' h / day';$('radiusValue').textContent=b.radius.toFixed(2);$('gravityValue').textContent=b.gravity.toFixed(2)+'×';$('waterValue').textContent=Math.round(b.water)+'%';$('iceValue').textContent=Math.round(b.ice)+'%';$('atmoValue').textContent=b.atmo.toFixed(2)+' atm';$('magneticValue').textContent=b.magnetic.toFixed(1)+'×'}
function syncBodyCard(b){const labels={star:['Star','Stellar fusion and plasma'],gas:['Gas giant','Hydrogen-rich atmosphere'],moon:['Natural satellite','Rocky or icy moon'],blackhole:['Black hole','Collapsed compact object'],rock:['Terrestrial planet','Editable rocky world']};const [label,summary]=labels[b.type]||labels.rock;$('classification').textContent=label;$('classificationSummary').textContent=summary;$('composition').textContent=b.type==='gas'?'Hydrogen, helium and trace ices':b.type==='star'?'Plasma and fusion products':b.type==='moon'?'Rock, ice and regolith':b.type==='blackhole'?'Collapsed mass':'Silicate rock and metal core';$('atmosphereSummary').textContent=b.atmo>0?`${b.atmo.toFixed(2)} atm`:'Vacuum';$('radiusSummary').textContent=`${b.radius.toFixed(2)} visual units`;$('gravitySummary').textContent=`${b.gravity.toFixed(2)}×`;const orb=$('bodyOrb');orb.style.background=b.type==='blackhole'?'radial-gradient(circle at 35% 30%,#343434,#000 58%)':`radial-gradient(circle at 34% 28%,#ffffff66,#ffffff00 17%),${b.color}`;orb.style.boxShadow=`0 0 28px ${b.color}66`}
function notice(s){$('message').textContent=s}
function syncCreatorTargets(){const select=$('customTarget');if(!select)return;const current=String(launchTargetId||select.value||'');select.innerHTML='';for(const body of bodies){const option=document.createElement('option');option.value=body.id;option.textContent=`${body.name} · ${body.type}`;select.append(option)}if(current&&bodies.some(b=>String(b.id)===current))select.value=current;else{const fallback=selected||bodies.find(b=>b.type==='star')||bodies[0];if(fallback){select.value=fallback.id;launchTargetId=fallback.id}}}
function openCreator(){if(selected)launchTargetId=selected.id;syncCreatorTargets();$('creator').hidden=false;notice('New planet studio opened · choose its orbit target')}
function chosenTarget(except=null){syncCreatorTargets();const picked=bodies.find(b=>String(b.id)===$('customTarget')?.value&&b!==except);if(picked)return picked;if(selected&&selected!==except)return selected;return bodies.filter(b=>b!==except).sort((a,b)=>b.mass-a.mass)[0]}
function orbit(parent,spec,distance,angle=Math.random()*Math.PI*2,inclination=.03){const speed=Math.sqrt(G*(parent.mass+(spec.mass||1/EARTH))/distance);return create({...spec,parentId:parent.id,p:[parent.p[0]+Math.cos(angle)*distance,parent.p[1]+Math.sin(angle)*distance*Math.sin(inclination),parent.p[2]+Math.sin(angle)*distance*Math.cos(inclination)],v:[parent.v[0]-Math.sin(angle)*speed,parent.v[1]+Math.cos(angle)*speed*Math.sin(inclination),parent.v[2]+Math.cos(angle)*speed*Math.cos(inclination)]})}
function solar(){for(const b of [...bodies])destroy(b);years=0;const sun=create({name:'Sun',type:'star',mass:1,radius:1.6,color:'#fff0cb',temp:5778,atmo:0,water:0,ice:0,magnetic:.02});const data=[['Mercury',.39,.055,.19,'#9e9389'],['Venus',.72,.815,.33,'#d7c6a5'],['Earth',1,1,.36,'#79b6ff'],['Mars',1.52,.107,.27,'#b87453'],['Jupiter',5.2,317.8,.94,'#c8b399'],['Saturn',9.58,95.2,.80,'#d3c39b'],['Uranus',19.2,14.5,.61,'#98cbd0'],['Neptune',30.05,17.1,.59,'#739cc4']];const planets={};data.forEach((d,i)=>{const b=orbit(sun,{name:d[0],mass:d[2]/EARTH,radius:d[3],color:d[4],type:i>3?'gas':'rock',ring:i===5,atmo:i===0?0:(i===2?1:.3),tilt:i===6?98:23,temp:i===2?288:120,water:i===2?71:(i===3?2:0),ice:i===2?18:(i===3?12:0),magnetic:i===2?1:(i===4?4.3:.25)},d[1],i*.79+.4,i===0?.12:.025);planets[d[0]]=b});const moon=(parent,name,mass,radius,distance,angle)=>orbit(parent,{name,type:'moon',mass:mass/EARTH,radius,color:'#aaa89f',atmo:0,water:2,ice:18,magnetic:.05},distance,angle,.15);moon(planets.Earth,'Moon',.0123,.10,.00257,0);moon(planets.Jupiter,'Io',.015,.07,.0042,.3);moon(planets.Jupiter,'Europa',.008,.065,.0067,1.4);moon(planets.Jupiter,'Ganymede',.025,.085,.0072,2.5);moon(planets.Jupiter,'Callisto',.018,.08,.0126,3.7);moon(planets.Saturn,'Titan',.0225,.085,.20,.8);moon(planets.Uranus,'Titania',.00059,.055,.16,2.2);moon(planets.Neptune,'Triton',.0036,.065,.16,4.1);choose(planets.Earth);buildAsteroidBelt();camera.position.set(24,30,57);controls.target.set(0,0,0);notice('Solar system ready · 8 planets, 8 major moons, and asteroid belt');}
function catalogSpec(type){return {rock:{name:'New rocky world',type:'rock',mass:1/EARTH,radius:.4,color:'#b29c85',water:20,ice:4},gas:{name:'New gas giant',type:'gas',mass:80/EARTH,radius:.85,color:'#bca78d',ring:true,atmo:2},moon:{name:'New moon',type:'moon',mass:.012/EARTH,radius:.12,color:'#aaa9a0',atmo:0},star:{name:'Companion star',type:'star',mass:.3,radius:1.2,color:'#ffd2a5',atmo:0,temp:3800},blackhole:{name:'Black hole',type:'blackhole',mass:3,radius:.6,color:'#000000',atmo:0}}[type]}
function spawn(type){if(bodies.length>=60){notice('60-body limit reached');return}beginPlacement(catalogSpec(type))}
function impact(){if(!selected)return;const target=selected,boost=Number($('impactSpeed').value);const offset=(target.radius+.15)/AU*1.1;create({name:'Impactor',type:'moon',mass:.08/EARTH,radius:.1,color:'#665c53',atmo:.02,water:8,ice:12,p:[target.p[0]+offset,target.p[1]+offset*.3,target.p[2]],v:[target.v[0]-15*boost,target.v[1]-4.5*boost,target.v[2]]});notice(['Slow','Fast','Hypervelocity'][boost<.8?0:boost<1.3?1:2]+' impactor launched toward '+target.name)}
function collide(){for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){let a=bodies[i],b=bodies[j];const distance=Math.hypot(...a.p.map((v,k)=>v-b.p[k]));if(!Number.isFinite(distance)||distance>Math.max(.00002,(a.radius+b.radius)*.0025))continue;if(b.mass>a.mass)[a,b]=[b,a];const am=a.mass,bm=b.mass,m=am+bm,dv=Math.hypot(...a.v.map((v,k)=>v-b.v[k]));if(!Number.isFinite(m)||!Number.isFinite(dv)||m<=0)continue;const strip=Math.max(.03,1-dv*.035);a.v=a.v.map((v,k)=>(v*am+b.v[k]*bm)/m);a.p=a.p.map((v,k)=>(v*am+b.p[k]*bm)/m);a.atmo=((a.atmo*am+b.atmo*bm)/m)*strip;a.water=(a.water*am+b.water*bm)/m;a.ice=Math.max(0,(a.ice*am+b.ice*bm)/m-dv*.4);a.magnetic=(a.magnetic*am+b.magnetic*bm)/m;a.mass=m;a.radius=Math.cbrt(a.radius**3+b.radius**3);a.temp=Math.min(15000,a.temp+dv*300);a.impacts=(a.impacts||0)+(b.impacts||0)+1;addImpactHotspot(a,b,Math.min(1.2,.35+dv*.045));a.heat=.35;refreshSurface(a);const wave=new T.Mesh(new T.SphereGeometry(1,24,16),new T.MeshBasicMaterial({color:dv>12?0xfff0c2:0xffa45d,wireframe:true,transparent:true,opacity:.8,blending:T.AdditiveBlending,depthWrite:false}));wave.position.set(...a.p.map(v=>v*AU));scene.add(wave);effects.push({mesh:wave,age:0,r:a.radius});const wasSelected=selected===b||selected===a,hitName=b.name;destroy(b);if(wasSelected)choose(a);notice('Impact on '+a.name+' · localized hot spot, debris wave, and '+Math.round((1-strip)*100)+'% atmosphere stripped');return}}
function stellarBurst(kind){if(!selected||selected.type!=='star'){notice('Select a star to trigger this event');return}const star=selected,verts=[],r=random(Date.now()%99991);for(let i=0;i<180;i++){const v=new T.Vector3(r()*2-1,r()*2-1,r()*2-1).normalize().multiplyScalar(.7+r()*.7);verts.push(v.x,v.y,v.z)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));const cloud=new T.Points(geo,new T.PointsMaterial({color:kind==='flare'?0xffc36b:0xeaf6ff,size:.07,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false}));cloud.position.copy(star.mesh.position);scene.add(cloud);effects.push({mesh:cloud,age:0,r:star.radius});for(const b of bodies){if(b===star)continue;const d=Math.max(.1,Math.hypot(...b.p.map((v,i)=>v-star.p[i])));b.temp+=kind==='flare'?Math.min(700,80/d):Math.min(6000,1200/d);if(kind==='supernova')b.v=b.v.map((v,i)=>v+(b.p[i]-star.p[i])/d*.18/d)}if(kind==='supernova'){star.type='blackhole';star.color='#000000';star.mass=Math.max(3,star.mass*.25);star.radius=.7;star.atmo=0;star.material.map=null;star.material.color.set('#000000');star.material.emissive.set('#000000');setRings(star,true);choose(star);notice('Supernova erupted · remnant collapsed into a black hole')}else notice('Coronal mass ejection released · nearby worlds heated')}
const ray=new T.Raycaster(),pointer=new T.Vector2(),ground=new T.Plane(new T.Vector3(0,1,0),0);let down=[0,0];
function worldAt(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const point=new T.Vector3();return ray.ray.intersectPlane(ground,point)?point:null}
function beginPlacement(spec){placeSpec={...spec};moving=null;placementRing.visible=true;renderer.domElement.style.cursor='crosshair';$('creator').hidden=true;notice('Move the glowing ring, then click to place '+spec.name)}
function placeAt(world){if(!placeSpec||!world)return;const p=world.toArray().map(v=>v/AU);let parent=chosenTarget();if(!parent){const b=create({...placeSpec,p,v:[0,0,0]});choose(b);return}const dx=p[0]-parent.p[0],dz=p[2]-parent.p[2],d=Math.max(.25,Math.hypot(dx,dz)),s=Math.sqrt(G*(parent.mass+(placeSpec.mass||1/EARTH))/d),nx=dx/d,nz=dz/d;const b=create({...placeSpec,parentId:parent.id,p:[parent.p[0]+nx*d,p[1],parent.p[2]+nz*d],v:[parent.v[0]-nz*s,parent.v[1],parent.v[2]+nx*s]});choose(b);placeSpec=null;placementRing.visible=false;renderer.domElement.style.cursor='';notice(b.name+' placed into a 3D orbit around '+parent.name)}
function bodyHit(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObjects(bodies.filter(b=>b.mesh.visible).map(b=>b.mesh),false)[0]?.object.userData.body}
renderer.domElement.addEventListener('pointerdown',e=>{if(following&&!moveMode&&!placeSpec)following=false;down=[e.clientX,e.clientY];if(moveMode&&!placeSpec){const hit=bodyHit(e);if(hit){moving=hit;controls.enabled=false;choose(hit);notice('Dragging '+hit.name+' · release to set position')}}});
renderer.domElement.addEventListener('pointermove',e=>{const point=worldAt(e);if(placeSpec&&point){placementRing.position.copy(point);placementRing.scale.setScalar(Math.max(.25,placeSpec.radius||.4))}if(moving&&point){moving.p=point.toArray().map(v=>v/AU);moving.v=[0,0,0];moving.trail=[]}});
renderer.domElement.addEventListener('pointerup',e=>{if(moving){moving=null;controls.enabled=true;notice('Body moved · velocity reset for a fresh orbit');return}if(placeSpec){placeAt(worldAt(e));return}if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const hit=bodyHit(e);if(hit)choose(hit)});renderer.domElement.addEventListener('dblclick',()=>follow());controls.addEventListener('start',()=>following=false);renderer.domElement.addEventListener('wheel',()=>{following=false},{passive:true});
function follow(){if(!selected)return;following=true;const pos=selected.mesh.position;controls.target.copy(pos);camera.position.copy(pos).add(new T.Vector3(selected.radius*5,selected.radius*3,selected.radius*8));followOffset.copy(camera.position).sub(pos);notice('Following '+selected.name+' · camera locked to its moving frame')}
function orbitSelected(){if(!selected){notice('Select a body before using Orbit');return}const primary=chosenTarget(selected);if(!primary){notice('Orbit needs another star, planet, or primary body');return}const dx=selected.p[0]-primary.p[0],dz=selected.p[2]-primary.p[2],r=Math.max(.25,Math.hypot(dx,dz)),speed=Math.sqrt(G*(primary.mass+selected.mass)/r);selected.v=[primary.v[0]-dz/r*speed,selected.v[1],primary.v[2]+dx/r*speed];selected.parentId=primary.id;selected.trail=[];notice(selected.name+' placed on a stable circular orbit around '+primary.name)}
function advanceCentury(){if(!selected){notice('Select a body before using Century');return}const primary=chosenTarget(selected);if(!primary){notice('Century travel needs another primary body');return}const dx=selected.p[0]-primary.p[0],dz=selected.p[2]-primary.p[2],r=Math.max(.25,Math.hypot(dx,dz)),angular=Math.sqrt(G*(primary.mass+selected.mass)/(r*r*r)),advance=angular*100;const c=Math.cos(advance),s=Math.sin(advance),x=dx*c-dz*s,z=dx*s+dz*c;selected.p[0]=primary.p[0]+x;selected.p[2]=primary.p[2]+z;orbitSelected();years+=100;notice(selected.name+' advanced by one century around '+primary.name)}
$('focus').onclick=follow;$('impact').onclick=impact;$('reset').onclick=solar;$('clear').onclick=()=>{for(const b of [...bodies])destroy(b);choose(null);years=0;notice('Universe cleared · add a body to begin')};$('fit').onclick=()=>{following=false;controls.target.set(0,0,0);const extent=Math.max(10,...bodies.map(b=>Math.hypot(...b.p)*AU));camera.position.set(extent*.5,extent*.9,extent*1.6)};$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'Ⅱ':'▶';$('pause').setAttribute('aria-label',playing?'Pause':'Play')};$('rings').onclick=()=>{if(selected){setRings(selected);notice((selected.ring?'Rings generated around ':'Rings removed from ')+selected.name)}};$('blackhole').onclick=()=>{if(!selected)return;selected.type='blackhole';selected.mass=Math.max(selected.mass,3);selected.atmo=0;selected.color='#000000';selected.material.map=null;selected.material.color.set('#000000');selected.material.emissive.set('#000000');setRings(selected,true);choose(selected);notice(selected.name+' collapsed into a black hole')};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>spawn(b.dataset.type));$('orbitTool').onclick=orbitSelected;$('newPlanet').onclick=openCreator;$('zoneTool').onclick=toggleZones;$('impactTool').onclick=impact;$('centuryTool').onclick=advanceCentury;
$('moveMode').onclick=()=>{moveMode=!moveMode;placeSpec=null;placementRing.visible=false;$('moveMode').classList.toggle('primary',moveMode);$('moveMode').textContent=moveMode?'✥ Move: ON':'✥ Move';notice(moveMode?'Drag any visible planet to reposition it':'Camera orbit mode restored')};$('customPlanet').onclick=openCreator;$('customTarget').onchange=e=>{launchTargetId=Number(e.target.value)||null;const target=bodies.find(b=>b.id===launchTargetId);if(target)notice('Launch target set to '+target.name)};$('customWater').oninput=e=>$('customWaterValue').textContent=e.target.value+'%';$('placeCustom').onclick=()=>{const mass=Math.max(.0001,Number($('customMass').value)||1);beginPlacement({name:$('customName').value.trim()||'My planet',type:($('customClass').value==='molten'?'rock':$('customClass').value),mass:mass/EARTH,radius:Math.min(3,Math.max(.12,.36*Math.cbrt(mass))),color:$('customColor').value,water:Number($('customWater').value),ocean:$('customOcean').value,land:$('customLand').value,atmoColor:$('customAtmo').value,atmo:.8,ring:$('customRings').checked})};$('moltenPlanet').onclick=()=>beginPlacement({name:'Molten world',type:'rock',mass:1.5/EARTH,radius:.42,color:'#d65328',water:0,ice:0,land:'#551313',atmo:1.4,atmoColor:'#ff8c4b',temp:1500});$('regularPlanet').onclick=()=>beginPlacement({name:'Regular planet',type:'rock',mass:1/EARTH,radius:.36,color:'#78aee8',water:65,ice:12,ocean:'#185aa3',land:'#5c8a50',atmo:1,atmoColor:'#8cd8ff'});
$('name').oninput=e=>{if(selected){selected.name=e.target.value;$('title').textContent=selected.name}};const applyMass=e=>{const n=Number(e.target.value);if(selected&&Number.isFinite(n)&&n>0&&n<1e9){selected.mass=n/EARTH;selected.radius=Math.min(3,Math.max(.08,.36*Math.cbrt(n)));$('radius').value=selected.radius;syncOutputs(selected)}};$('mass').oninput=applyMass;$('mass').onchange=applyMass;$('color').oninput=e=>{if(selected){selected.color=e.target.value;selected.material.color.set(e.target.value);if(selected.type==='star')selected.material.emissive.set(e.target.value)}};for(const [field,key]of [['radius','radius'],['tilt','tilt'],['dayLength','dayLength'],['atmo','atmo'],['gravity','gravity'],['water','water'],['ice','ice'],['magnetic','magnetic']])$(field).oninput=e=>{if(selected){selected[key]=Number(e.target.value);syncOutputs(selected);if(key==='water'||key==='ice')refreshSurface(selected)}};for(const [field,key]of [['ocean','ocean'],['land','land'],['atmoColor','atmoColor']])$(field).oninput=e=>{if(selected){selected[key]=e.target.value;if(key!=='atmoColor')refreshSurface(selected)}};for(const [field,i]of [['vx',0],['vy',1],['vz',2]])$(field).onchange=e=>{const n=Number(e.target.value);if(selected&&Number.isFinite(n))selected.v[i]=n};$('remove').onclick=()=>{if(selected){destroy(selected);choose(bodies[0]||null)}};window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.code==='Space'){e.preventDefault();$('pause').click()}if(e.key.toLowerCase()==='f')follow();if((e.key==='Delete'||e.key==='Backspace')&&selected)$('remove').click()});
const serial=b=>Object.fromEntries(['name','type','mass','radius','color','p','v','tilt','dayLength','atmo','atmoColor','magnetic','gravity','water','ice','ocean','land','impacts','temp','ring','parentId'].map(k=>[k,b[k]]));$('save').onclick=()=>{try{localStorage.setItem('orbital3d',JSON.stringify({years,bodies:bodies.map(serial)}));notice('Universe saved on this device')}catch{notice('Could not save: browser storage unavailable')}};$('load').onclick=()=>{try{const data=JSON.parse(localStorage.getItem('orbital3d'));if(!data?.bodies?.length||data.bodies.length>60)throw Error();for(const b of data.bodies){if(!b.p?.every(Number.isFinite)||!b.v?.every(Number.isFinite)||!Number.isFinite(b.mass)||b.mass<=0)throw Error()}for(const b of [...bodies])destroy(b);data.bodies.forEach(create);years=data.years||0;choose(bodies[0]);notice('Saved universe restored')}catch{notice('No valid saved universe on this device')}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});let last=performance.now(),frame=0;
function updateOrbitGuides(){for(const guide of orbitGuides.children){guide.geometry.dispose();guide.material.dispose()}orbitGuides.clear();if(!$('trails').checked)return;for(const body of bodies){if(!body.parentId||body.type==='star')continue;const parent=bodies.find(b=>b.id===body.parentId);if(!parent)continue;const dx=body.p[0]-parent.p[0],dz=body.p[2]-parent.p[2],radius=Math.hypot(dx,dz)*AU;if(!Number.isFinite(radius)||radius<.2||radius>1500)continue;const curve=new T.EllipseCurve(0,0,radius,radius,0,Math.PI*2,false,0);const points=curve.getPoints(180).map(p=>new T.Vector3(parent.p[0]*AU+p.x,parent.p[1]*AU,parent.p[2]*AU+p.y));const highlighted=body===selected||parent===selected;const line=new T.LineLoop(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:highlighted?0x76d7ff:0x4d8edc,transparent:true,opacity:highlighted ? .88 : .34,blending:T.AdditiveBlending,depthWrite:false}));orbitGuides.add(line)}}
function animate(now){requestAnimationFrame(animate);const real=Math.max(0,Math.min((now-last)/1000,.05));last=now;if(playing){const requested=real*Number($('speed').value);let safe=.001;for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],d=Math.hypot(...a.p.map((v,k)=>v-b.p[k]));safe=Math.min(safe,Math.sqrt(Math.max(d,1e-5)**3/(G*(a.mass+b.mass)))/30)}const n=Math.min(24,Math.max(1,Math.ceil(requested/Math.max(safe,.0003)))),dt=Math.min(.003,requested/n);try{for(let k=0;k<n;k++){step(bodies,dt);collide()}}catch(error){playing=false;notice('Simulation paused safely · '+(error?.message||'physics error'));console.error(error)}for(const b of bodies){for(let i=0;i<3;i++){if(!Number.isFinite(b.p[i]))b.p[i]=0;if(!Number.isFinite(b.v[i]))b.v[i]=0}b.mass=Math.max(1e-12,Number.isFinite(b.mass)?b.mass:1/EARTH)}years+=dt*n}
asteroidBelt.visible=bodies.length>0;asteroidBelt.rotation.y+=real*.006;for(const b of bodies){const shown=b.type!=='moon'||$('moons').checked;b.mesh.position.set(...b.p.map(v=>v*AU));b.mesh.scale.setScalar(b.radius);b.mesh.rotation.z=T.MathUtils.degToRad(b.tilt);b.mesh.visible=shown;if(playing)b.mesh.rotation.y+=real*(24/Math.max(2,b.dayLength))*.08;b.atmosphere.position.copy(b.mesh.position);b.atmosphere.scale.setScalar(b.radius*1.045);b.atmosphere.material.uniforms.strength.value=Math.min(1.35,Math.pow(Math.max(0,b.atmo),.72)*.38);b.atmosphere.material.uniforms.tint.value.set(b.atmoColor);b.atmosphere.visible=shown&&b.atmo>0&&b.type!=='star';b.axis.visible=shown&&$('axes').checked;b.field.visible=shown&&b.magnetic>0;b.field.scale.setScalar(b.radius*(.8+Math.min(3,b.magnetic)*.16));b.field.children.forEach((loop,index)=>{loop.material.opacity=shown&&b.magnetic>0?Math.min(.5,.08+b.magnetic*.035)/(index+1):0});if(b.glow){b.glow.position.copy(b.mesh.position);b.glow.scale.setScalar(b.radius*9)}if(b.ringMesh){b.ringMesh.position.copy(b.mesh.position);b.ringMesh.scale.setScalar(b.radius);b.ringMesh.visible=shown}if(b.type!=='blackhole'){if(b.hotspots)for(const h of b.hotspots){h.age+=real;const pulse=.72+.28*Math.sin(h.age*12);h.mesh.material.opacity=Math.max(0,.95-h.age*.025)*pulse;h.mesh.scale.setScalar(pulse*(1+h.strength*.12))}if(b.heat){b.heat=Math.max(0,b.heat-real*.09);b.material.emissive.set(b.type==='star'?b.color:'#ff7a32');b.material.emissiveIntensity=.06+b.heat*.25}else{b.material.emissive.set(b.type==='star'?b.color:b.color);b.material.emissiveIntensity=b.type==='star'?2.5:.06}}b.line.visible=shown&&$('trails').checked;if(playing&&frame%4===0){b.trail.push(b.mesh.position.clone());const max=360;if(b.trail.length>max)b.trail.splice(0,b.trail.length-max);b.line.geometry.dispose();b.line.geometry=new T.BufferGeometry().setFromPoints(b.trail)}}
const climateSun=bodies.find(b=>b.type==='star');if(climateSun)for(const b of bodies){if(b===climateSun||b.type==='star'||b.type==='blackhole')continue;const distance=Math.max(.05,Math.hypot(...b.p.map((v,i)=>v-climateSun.p[i])));const equilibrium=278/Math.sqrt(distance);b.temp+=(equilibrium-b.temp)*Math.min(1,real*.12);const harsh=distance<.62||distance>2.4;if(harsh&&b.water>0&&playing){b.water=Math.max(0,b.water-real*Number($('speed').value)*18);b.ice=distance>2.4?Math.min(100,b.ice+real*Number($('speed').value)*8):Math.max(0,b.ice-real*Number($('speed').value)*5);if(frame%20===0)refreshSurface(b)}}if(frame%20===0)updateOrbitGuides();const sun=bodies.find(b=>b.type==='star');sunlight.visible=!!sun;if(sun)sunlight.position.copy(sun.mesh.position);if(selected){selectionRing.visible=selected.mesh.visible;selectionRing.position.copy(selected.mesh.position);selectionRing.scale.setScalar(selected.radius);selectionRing.quaternion.copy(camera.quaternion);$('temp').textContent=Math.round(selected.temp)+' K';$('velocity').textContent=(Math.hypot(...selected.v)*4.74).toFixed(1)+' km/s';$('impacts').textContent=selected.impacts||0;if(following){controls.target.copy(selected.mesh.position);camera.position.copy(selected.mesh.position).add(followOffset)}}else selectionRing.visible=false;
for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=real;e.mesh.scale.setScalar(e.r*(1+e.age*4));e.mesh.material.opacity=Math.max(0,.6-e.age*.25);if(e.age>2.4){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}
 $('clock').textContent=(years*365.25).toFixed(1)+' days';$('count').textContent=bodies.length+' bodies · '+(playing?'simulation running':'paused');controls.update();renderer.render(scene,camera);frame++}
const resetSolar=solar;$('reset').onclick=()=>{following=false;followOffset.set(0,0);resetSolar()};
/* Override the broad visual collision envelope with a compact AU-scale one.
   Stylized meshes are larger than their physical radii; this prevents moons
   from colliding with their parent on the first frame. */
const climateZones=new T.Group();climateZones.name='Climate zones';scene.add(climateZones);let zonesVisible=false;
function toggleZones(){zonesVisible=!zonesVisible;climateZones.clear();if(zonesVisible){const bands=[{radius:.18,color:0xff6b58,label:'ROCHE / TIDAL'},{radius:.42,color:0xff8d56,label:'HOT'},{radius:.72,color:0x4bd6a5,label:'HABITABLE'},{radius:1.65,color:0x7b8cff,label:'COLD'},{radius:2.4,color:0x6578b8,label:'DEAD / FROZEN'}];for(const band of bands){const mesh=new T.Mesh(new T.RingGeometry(band.radius*AU-.055,band.radius*AU+.055,160),new T.MeshBasicMaterial({color:band.color,transparent:true,opacity:.52,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.userData.zone=band.label;climateZones.add(mesh)}}climateZones.visible=zonesVisible;notice(zonesVisible?'Zones: Roche/tidal · hot · habitable · cold · dead/frozen':'Climate zones hidden')}
function climateTick(){const sun=bodies.find(b=>b.type==='star');if(!sun)return;for(const b of bodies){if(b===sun||b.type==='star'||b.type==='blackhole')continue;const d=Math.max(.05,Math.hypot(...b.p.map((v,i)=>v-sun.p[i])));const heating=Math.max(0,1/d);b.temp=Math.round(180+110*heating);if(b.water>0&&d<.82){b.water=Math.max(0,b.water-(.82-d)*.18);b.atmo=Math.max(.08,b.atmo-(.82-d)*.025);refreshSurface(b);if(b===selected)syncOutputs(b)}else if(d>1.8&&b.water<20)b.ice=Math.min(100,b.ice+.05)}}
/*
setInterval(climateTick,500);$('zoneTool').onclick=toggleZones;$('customClass').oninput=e=>{const cls=e.target.value;const preset=cls==='gas'?{type:'gas',radius:.85,water:0,ice:0,atmo:2,color:'#bca78d'}:cls==='redDwarf'?{type:'star',radius:.75,mass:.12,color:'#ff684f',temp:3200,atmo:0}:cls==='brownDwarf'?{type:'star',radius:.65,mass:.06,color:'#c47b58',temp:1400,atmo:0}:cls==='failedStar'?{type:'star',radius:.9,mass:.25,color:'#e6a06f',temp:2600,atmo:0}:cls==='yellowStar'?{type:'star',radius:1.4,mass:1,color:'#fff0cb',temp:5778,atmo:0}:cls==='blueGiant'?{type:'star',radius:2.2,mass:8,color:'#8fc5ff',temp:16000,atmo:0}:cls==='moon'?{type:'moon',radius:.12,water:2,ice:18,atmo:0,color:'#aaa9a0'}:cls==='molten'?{type:'rock',radius:.42,water:0,ice:0,atmo:1.4,color:'#d65328',temp:1500}:{type:'rock',radius:.36,water:55,ice:12,atmo:1,color:'#78aee8'};e.target.dataset.preset=JSON.stringify(preset)};
*/
/* Magnetic-field visuals, body clearance, and a compact star-type chooser. */
const starTypeSelect=document.createElement('select');starTypeSelect.id='starType';starTypeSelect.innerHTML='<option value="yellow">Yellow star</option><option value="redDwarf">Red dwarf</option><option value="brownDwarf">Brown dwarf</option><option value="failed">Failed star</option><option value="blueGiant">Blue giant</option>';starTypeSelect.hidden=true;$('customClass').after(starTypeSelect);$('customClass').addEventListener('change',e=>{starTypeSelect.hidden=e.target.value!=='star'});
const starPresets={yellow:{mass:1,radius:1.6,color:'#fff0cb',temp:5778},redDwarf:{mass:.35,radius:1.0,color:'#ff8a61',temp:3200},brownDwarf:{mass:22,radius:1.1,color:'#b97752',temp:1500},failed:{mass:8,radius:.8,color:'#c06655',temp:900},blueGiant:{mass:12,radius:2.2,color:'#9ec9ff',temp:22000}};
$('placeCustom').onclick=()=>{const cls=$('customClass').value,star=starPresets[$('starType').value]||starPresets.yellow;const base=cls==='star'?{name:starTypeSelect.options[starTypeSelect.selectedIndex].text,type:'star',mass:star.mass/EARTH,radius:star.radius,color:star.color,temp:star.temp,atmo:0}:cls==='gas'?{name:'New gas giant',type:'gas',mass:80/EARTH,radius:.85,color:'#bca78d',water:0,ice:0,atmo:2,ring:$('customRings').checked}:cls==='moon'?{name:'New moon',type:'moon',mass:.012/EARTH,radius:.12,color:'#aaa9a0',water:2,ice:18,atmo:0}:cls==='molten'?{name:'Molten planet',type:'rock',mass:1.5/EARTH,radius:.42,color:'#d65328',water:0,ice:0,atmo:1.4,temp:1500}:{name:$('customName').value.trim()||'My planet',type:'rock',mass:Math.max(.0001,Number($('customMass').value)||1)/EARTH,radius:Math.min(3,Math.max(.12,.36*Math.cbrt(Math.max(.0001,Number($('customMass').value)||1)))),color:$('customColor').value,water:Number($('customWater').value),ocean:$('customOcean').value,land:$('customLand').value,atmoColor:$('customAtmo').value,atmo:.8,ring:$('customRings').checked};beginPlacement(base)};
$('radius').addEventListener('input',()=>{if(!selected)return;const primary=bodies.filter(b=>b!==selected&&b.type==='star').sort((a,b)=>Math.hypot(...a.p.map((v,i)=>v-selected.p[i]))-Math.hypot(...b.p.map((v,i)=>v-selected.p[i])))[0];if(primary){const dx=selected.p[0]-primary.p[0],dz=selected.p[2]-primary.p[2],d=Math.hypot(dx,dz)||1,min=(selected.radius+primary.radius)*.7/AU;if(d<min){selected.p[0]=primary.p[0]+dx/d*min;selected.p[2]=primary.p[2]+dz/d*min;orbitSelected()}}});
renderer.domElement.addEventListener('pointerdown',e=>{if(following&&!bodyHit(e))following=false});
setInterval(()=>{for(const b of bodies){if(b.field){b.field.position.copy(b.mesh.position);b.field.scale.setScalar(Math.max(.05,b.radius*(.72+Math.min(4,b.magnetic)*.16)));b.field.visible=b.mesh.visible&&b.magnetic>0}if(b.atmosphere){b.atmosphere.material.uniforms.strength.value=Math.min(1.4,Math.max(0,b.atmo)*.26);b.atmosphere.material.opacity=Math.min(1,Math.max(.06,b.atmo*.12))}}},120);
solar();following=false;followOffset.set(0,0);camera.position.set(22,28,58);controls.target.set(0,0,0);camera.lookAt(0,0,0);requestAnimationFrame(animate);
