import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {step,G} from './physics.mjs';
const $=id=>document.getElementById(id), AU=10, EARTH=332946;
const renderer=new T.WebGLRenderer({canvas:$('universe'),antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new T.Scene();scene.background=new T.Color('#03060c');
const camera=new T.PerspectiveCamera(45,innerWidth/innerHeight,.01,5000);camera.position.set(32,45,84);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=1;controls.maxDistance=900;controls.target.set(0,0,0);
scene.add(new T.AmbientLight(0xa6bad1,.23));
const sunlight=new T.PointLight(0xfff4df,35,0,1);scene.add(sunlight);
const geometry=new T.SphereGeometry(1,64,40);
const textureLoader=new T.TextureLoader();const earthTexture=textureLoader.load('./assets/earth.jpg');earthTexture.colorSpace=T.SRGBColorSpace;
let bodies=[],selected=null,following=false,playing=true,years=0,id=0;const effects=[];
const random=(seed)=>{let s=seed;return()=>((s=s*16807%2147483647)-1)/2147483646};
function surface(type,seed){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=random(seed+191);x.fillStyle=type==='gas'?'#c4b297':'#8b8c86';x.fillRect(0,0,512,256);for(let i=0;i<1800;i++){if(type==='gas'){const y=r()*256;x.fillStyle=`rgba(${r()>.5?'93,74,59':'236,216,181'},${r()*.22})`;x.fillRect(0,y,512,r()*5+1)}else{x.fillStyle=`rgba(${r()>.5?'35,30,26':'235,227,209'},${r()*.2})`;x.beginPath();x.arc(r()*512,r()*256,r()*4+.5,0,7);x.fill()}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
function halo(color){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,1,64,64,64);g.addColorStop(0,'#ffffff');g.addColorStop(.13,color);g.addColorStop(.3,color+'44');g.addColorStop(1,color+'00');x.fillStyle=g;x.fillRect(0,0,128,128);return new T.CanvasTexture(c)}
const glowMap=halo('#ffd5a0');
const starGeo=new T.BufferGeometry(),positions=[],colors=[];const rng=random(333);for(let i=0;i<6500;i++){const angle=rng()*Math.PI*2;const z=i<4200?(rng()+rng()+rng()-1.5)*.28:rng()*2-1;const rr=Math.sqrt(Math.max(0,1-z*z)),dist=650+rng()*600;positions.push(Math.cos(angle)*rr*dist,z*dist,Math.sin(angle)*rr*dist);const c=new T.Color(rng()<.2?'#ffe1b6':'#bbd8ff');c.multiplyScalar(.25+rng()*.75);colors.push(c.r,c.g,c.b)}starGeo.setAttribute('position',new T.Float32BufferAttribute(positions,3));starGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));scene.add(new T.Points(starGeo,new T.PointsMaterial({size:1.1,vertexColors:true,transparent:true,opacity:.85,sizeAttenuation:true})));
const selectionRing=new T.Mesh(new T.RingGeometry(1.15,1.17,96),new T.MeshBasicMaterial({color:0xa7e6df,side:T.DoubleSide,transparent:true,opacity:.65}));scene.add(selectionRing);
function create(spec){const b={id:++id,name:'World '+id,type:'rock',mass:1/EARTH,radius:.45,color:'#adbac2',p:[0,0,0],v:[0,0,0],tilt:23,atmo:.08,temp:280,trail:[],...spec};
 const map=b.name==='Earth'?earthTexture:surface(b.type,b.id);b.material=new T.MeshStandardMaterial({map:b.type==='star'||b.type==='blackhole'?null:map,color:b.name==='Earth'?'#ffffff':b.color,roughness:.86,metalness:0});
 if(b.type==='star'){b.material.emissive=new T.Color(b.color);b.material.emissiveIntensity=2.5}if(b.type==='blackhole'){b.material.color.set('#000000');b.material.roughness=1}
 b.mesh=new T.Mesh(geometry,b.material);b.mesh.userData.body=b;scene.add(b.mesh);
 b.atmosphere=new T.Mesh(geometry,new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,uniforms:{tint:{value:new T.Color(0x76bfff)},strength:{value:b.atmo}},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.); n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'uniform vec3 tint; uniform float strength; varying vec3 n;varying vec3 v;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(v))),3.);gl_FragColor=vec4(tint,rim*strength);}' }));scene.add(b.atmosphere);
 b.axis=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0,-1.6,0),new T.Vector3(0,1.6,0)]),new T.LineBasicMaterial({color:0x9fdacf,transparent:true,opacity:.5}));b.mesh.add(b.axis);
 if(b.type==='star'){b.glow=new T.Sprite(new T.SpriteMaterial({map:glowMap,color:b.color,blending:T.AdditiveBlending,transparent:true,depthWrite:false}));scene.add(b.glow)}
 if(b.ring||b.type==='blackhole'){const ringGeo=new T.RingGeometry(b.type==='blackhole'?1.5:1.35,2.3,128,4);b.ringMesh=new T.Mesh(ringGeo,new T.MeshBasicMaterial({color:b.type==='blackhole'?0xffb76b:0xbaad92,side:T.DoubleSide,transparent:true,opacity:.58}));b.ringMesh.rotation.x=Math.PI/2.3;scene.add(b.ringMesh)}
 b.line=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:b.type==='star'?0xcc9f68:0x466578,transparent:true,opacity:.38}));scene.add(b.line);bodies.push(b);return b;
}
function destroy(b){for(const key of ['mesh','atmosphere','glow','ringMesh','line'])if(b[key])scene.remove(b[key]);b.material.map!==earthTexture&&b.material.map?.dispose();b.material.dispose();b.atmosphere.material.dispose();b.line.geometry.dispose();b.line.material.dispose();b.glow?.material.dispose();b.ringMesh?.geometry.dispose();b.ringMesh?.material.dispose();b.axis.geometry.dispose();b.axis.material.dispose();bodies=bodies.filter(x=>x!==b)}
function choose(b){selected=b;following=false;if(!b){$('inspector').hidden=true;return}$('inspector').hidden=false;$('title').textContent=b.name;$('kind').textContent={star:'Stellar body',rock:'Terrestrial world',gas:'Gas giant',moon:'Natural satellite',blackhole:'Compact object'}[b.type];$('name').value=b.name;$('mass').value=(b.mass*EARTH).toPrecision(5);$('color').value=b.color;$('radius').value=b.radius;$('tilt').value=b.tilt;$('atmo').value=b.atmo;notice(b.name+' selected · double-click to follow')}
function notice(s){$('message').textContent=s}
function orbit(parent,spec,distance,angle=Math.random()*Math.PI*2,inclination=.03){const speed=Math.sqrt(G*(parent.mass+(spec.mass||1/EARTH))/distance);return create({...spec,p:[parent.p[0]+Math.cos(angle)*distance,parent.p[1]+Math.sin(angle)*distance*Math.sin(inclination),parent.p[2]+Math.sin(angle)*distance*Math.cos(inclination)],v:[parent.v[0]-Math.sin(angle)*speed,parent.v[1]+Math.cos(angle)*speed*Math.sin(inclination),parent.v[2]+Math.cos(angle)*speed*Math.cos(inclination)]})}
function solar(){for(const b of [...bodies])destroy(b);years=0;const sun=create({name:'Sun',type:'star',mass:1,radius:1.6,color:'#fff0cb',temp:5778,atmo:0});const data=[['Mercury',.39,.055,.19,'#9e9389'],['Venus',.72,.815,.33,'#d7c6a5'],['Earth',1,1,.36,'#79b6ff'],['Mars',1.52,.107,.27,'#b87453'],['Jupiter',5.2,317.8,.94,'#c8b399'],['Saturn',9.58,95.2,.80,'#d3c39b'],['Uranus',19.2,14.5,.61,'#98cbd0'],['Neptune',30.05,17.1,.59,'#739cc4']];let earth;data.forEach((d,i)=>{const b=orbit(sun,{name:d[0],mass:d[2]/EARTH,radius:d[3],color:d[4],type:i>3?'gas':'rock',ring:i===5,atmo:i===0?0:.25,tilt:i===6?98:23,temp:i===2?288:120},d[1],i*.79+.4,i===0?.12:.025);if(i===2)earth=b});orbit(earth,{name:'Moon',type:'moon',mass:.0123/EARTH,radius:.10,color:'#aaa89f',atmo:0},.10,0,.15);choose(earth);camera.position.set(24,30,57);controls.target.set(0,0,0);notice('Solar system ready · 3D experiment');}
function spawn(type){if(bodies.length>=60){notice('60-body limit reached');return}const parent=selected||bodies.find(b=>b.type==='star');if(!parent){choose(create({type}));return}const specs={rock:{name:'New rocky world',type:'rock',radius:.4,color:'#b29c85'},gas:{name:'New gas giant',type:'gas',mass:80/EARTH,radius:.85,color:'#bca78d',ring:true},moon:{name:'New moon',type:'moon',mass:.012/EARTH,radius:.12,color:'#aaa9a0',atmo:0},star:{name:'Companion star',type:'star',mass:.3,radius:1.2,color:'#ffd2a5',atmo:0,temp:3800},blackhole:{name:'Black hole',type:'blackhole',mass:3,radius:.6,color:'#000000',atmo:0}};const s=specs[type];const d=Math.max((parent.radius+s.radius)*.3,parent.type==='star'?3:.35);choose(orbit(parent,s,d));notice('Created '+selected.name+' in a 3D orbit')}
function impact(){if(!selected)return;const target=selected;const offset=(target.radius+.15)/AU*1.1;const b=create({name:'Impactor',type:'moon',mass:.08/EARTH,radius:.1,color:'#665c53',atmo:0,p:[target.p[0]+offset,target.p[1]+offset*.3,target.p[2]],v:[target.v[0]-15,target.v[1]-4.5,target.v[2]]});notice('Impactor launched toward '+target.name)}
function collide(){for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){let a=bodies[i],b=bodies[j];if(Math.hypot(...a.p.map((v,k)=>v-b.p[k]))>(a.radius+b.radius)/AU*.65)continue;if(b.mass>a.mass)[a,b]=[b,a];const m=a.mass+b.mass;const dv=Math.hypot(...a.v.map((v,k)=>v-b.v[k]));a.v=a.v.map((v,k)=>(v*a.mass+b.v[k]*b.mass)/m);a.p=a.p.map((v,k)=>(v*a.mass+b.p[k]*b.mass)/m);a.mass=m;a.radius=Math.cbrt(a.radius**3+b.radius**3);a.temp=Math.min(15000,a.temp+dv*300);a.heat=1;const wave=new T.Mesh(new T.SphereGeometry(1,24,16),new T.MeshBasicMaterial({color:0xffa45d,wireframe:true,transparent:true,opacity:.6}));wave.position.set(...a.p.map(v=>v*AU));scene.add(wave);effects.push({mesh:wave,age:0,r:a.radius});const wasSelected=selected===b||selected===a;notice(a.name+' absorbed '+b.name+' · mass and heat updated');destroy(b);if(wasSelected)choose(a);return}}
const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(bodies.map(b=>b.mesh),false)[0];if(hit)choose(hit.object.userData.body)});renderer.domElement.addEventListener('dblclick',()=>follow());controls.addEventListener('start',()=>following=false);
function follow(){if(!selected)return;following=true;const pos=selected.mesh.position;controls.target.copy(pos);camera.position.copy(pos).add(new T.Vector3(selected.radius*5,selected.radius*3,selected.radius*8));notice('Following '+selected.name)}
$('focus').onclick=follow;$('impact').onclick=impact;$('reset').onclick=solar;$('fit').onclick=()=>{following=false;controls.target.set(0,0,0);const extent=Math.max(10,...bodies.map(b=>Math.hypot(...b.p)*AU));camera.position.set(extent*.5,extent*.9,extent*1.6)};$('pause').onclick=()=>{playing=!playing;$('pause').textContent=playing?'Ⅱ':'▶';$('pause').setAttribute('aria-label',playing?'Pause':'Play')};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>spawn(b.dataset.type));
$('name').oninput=e=>{if(selected){selected.name=e.target.value;$('title').textContent=selected.name}};$('mass').onchange=e=>{const n=Number(e.target.value);if(selected&&Number.isFinite(n)&&n>0&&n<1e9)selected.mass=n/EARTH};$('color').oninput=e=>{if(selected){selected.color=e.target.value;selected.material.color.set(e.target.value);if(selected.type==='star')selected.material.emissive.set(e.target.value)}};for(const [field,key]of [['radius','radius'],['tilt','tilt'],['atmo','atmo']])$(field).oninput=e=>{if(selected)selected[key]=Number(e.target.value)};$('remove').onclick=()=>{if(selected){destroy(selected);choose(bodies[0]||null)}};
const serial=b=>Object.fromEntries(['name','type','mass','radius','color','p','v','tilt','atmo','temp','ring'].map(k=>[k,b[k]]));$('save').onclick=()=>{try{localStorage.setItem('orbital3d',JSON.stringify({years,bodies:bodies.map(serial)}));notice('Universe saved on this device')}catch{notice('Could not save: browser storage unavailable')}};$('load').onclick=()=>{try{const data=JSON.parse(localStorage.getItem('orbital3d'));if(!data?.bodies?.length||data.bodies.length>60)throw Error();for(const b of data.bodies){if(!b.p?.every(Number.isFinite)||!b.v?.every(Number.isFinite)||!Number.isFinite(b.mass)||b.mass<=0)throw Error()}for(const b of [...bodies])destroy(b);data.bodies.forEach(create);years=data.years||0;choose(bodies[0]);notice('Saved universe restored')}catch{notice('No valid saved universe on this device')}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});let last=performance.now(),frame=0;
function animate(now){requestAnimationFrame(animate);const real=Math.max(0,Math.min((now-last)/1000,.05));last=now;if(playing){const requested=real*Number($('speed').value);let safe=.001;for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],d=Math.hypot(...a.p.map((v,k)=>v-b.p[k]));safe=Math.min(safe,Math.sqrt(Math.max(d,1e-5)**3/(G*(a.mass+b.mass)))/30)}const n=Math.min(50,Math.max(1,Math.ceil(requested/safe))),dt=Math.min(safe,requested/n);for(let k=0;k<n;k++){step(bodies,dt);collide()}years+=dt*n}
 for(const b of bodies){b.mesh.position.set(...b.p.map(v=>v*AU));b.mesh.scale.setScalar(b.radius);b.mesh.rotation.z=T.MathUtils.degToRad(b.tilt);if(playing)b.mesh.rotation.y+=real*.08;b.atmosphere.position.copy(b.mesh.position);b.atmosphere.scale.setScalar(b.radius*1.045);b.atmosphere.material.uniforms.strength.value=b.atmo;b.atmosphere.visible=b.atmo>0&&b.type!=='star';b.axis.visible=$('axes').checked;if(b.glow){b.glow.position.copy(b.mesh.position);b.glow.scale.setScalar(b.radius*9)}if(b.ringMesh){b.ringMesh.position.copy(b.mesh.position);b.ringMesh.scale.setScalar(b.radius)}if(b.heat){b.heat=Math.max(0,b.heat-real*.04);b.material.emissive.set('#ff450b');b.material.emissiveIntensity=b.heat*1.3}b.line.visible=$('trails').checked;if(playing&&frame%4===0){b.trail.push(b.mesh.position.clone());if(b.trail.length>450)b.trail.shift();b.line.geometry.dispose();b.line.geometry=new T.BufferGeometry().setFromPoints(b.trail)}}
 const sun=bodies.find(b=>b.type==='star');sunlight.visible=!!sun;if(sun)sunlight.position.copy(sun.mesh.position);if(selected){selectionRing.visible=true;selectionRing.position.copy(selected.mesh.position);selectionRing.scale.setScalar(selected.radius);selectionRing.quaternion.copy(camera.quaternion);$('temp').textContent=Math.round(selected.temp)+' K';$('velocity').textContent=(Math.hypot(...selected.v)*4.74).toFixed(1)+' km/s';$('tiltValue').textContent=selected.tilt+'°';if(following){const d=selected.mesh.position.clone().sub(controls.target);camera.position.add(d);controls.target.copy(selected.mesh.position)}}else selectionRing.visible=false;
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=real;e.mesh.scale.setScalar(e.r*(1+e.age*4));e.mesh.material.opacity=Math.max(0,.6-e.age*.25);if(e.age>2.4){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}
 $('clock').textContent=(years*365.25).toFixed(1)+' days';$('count').textContent=bodies.length+' bodies · '+(playing?'simulation running':'paused');controls.update();renderer.render(scene,camera);frame++}
solar();requestAnimationFrame(animate);
